using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using UnityEditor;

namespace Yuffter.AudioManager
{
#if UNITY_EDITOR
    public static class AudioEnumGenerator
    {
        const string Output = "Assets/AudioManager/Generated/AudioIds.cs";

        [MenuItem("Tools/AudioManager/Generate Enums")]
        public static void Generate()
        {
            // AudioLibrary(SO)を探して取得
            var lib = AssetDatabase
                .FindAssets("t:AudioLibrary")
                .Select(g =>
                    AssetDatabase.LoadAssetAtPath<AudioLibrary>(AssetDatabase.GUIDToAssetPath(g))
                )
                .FirstOrDefault();
            if (lib == null)
                return;

            // 生成するコードを組み立てる
            var sb = new StringBuilder("// <auto-generated />\nnamespace Yuffter.AudioManager\n{\n");
            Append(sb, "Se", lib.Entries.Where(e => e.Category == AudioCategory.Se)); // カテゴリがSeのエントリのみを抽出してenum化
            Append(sb, "Bgm", lib.Entries.Where(e => e.Category == AudioCategory.Bgm)); // カテゴリがBgmのエントリのみを抽出してenum化
            sb.Append("}\n");

            var text = sb.ToString();
            Directory.CreateDirectory(Path.GetDirectoryName(Output));
            // 中身が同じなら書き込まない
            if (!File.Exists(Output) || File.ReadAllText(Output) != text)
            {
                File.WriteAllText(Output, text);
                AssetDatabase.ImportAsset(Output);
            }
        }

        static void Append(StringBuilder sb, string name, IEnumerable<AudioEntry> es)
        {
            sb.Append($"    public enum {name}\n    {{\n        None = 0,\n");
            foreach (var e in es)
                sb.Append($"        {Sanitize(e.Key)} = {e.Id},\n");
            sb.Append("    }\n");
        }

        static string Sanitize(
            string s
        ) // 識別子化（雑な例）
            => Regex.Replace(s, @"[^0-9A-Za-z_]", "_");
    }

    // Library 保存時に自動再生成
    class AudioLibraryPostprocessor : AssetPostprocessor
    {
        static void OnPostprocessAllAssets(string[] imported, string[] _, string[] __, string[] ___)
        {
            if (imported.Any(p => AssetDatabase.LoadAssetAtPath<AudioLibrary>(p) != null))
                AudioEnumGenerator.Generate();
        }
    }
#endif
}
